name: utils
description: A new Flutter package project.
version: 2.0.4
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: mobx

dependencies:
  flutter:
    sdk: flutter

  # State manager
  #! override
  mobx: any
  flutter_mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: flutter_mobx
  disposing:
    git:
      url: https://github.com/altynbek132/dart_disposing
      path: packages/disposing
  elementary:
    git:
      url: https://github.com/altynbek132/flutter-elementary
      path: packages/elementary

  # Other
  rxdart: ^0.27.7
  meta: ^1.11.0
  synchronized: ^3.0.0
  reactive_forms: ^18.0.0
  yx_scope: ^1.0.0
  yx_scope_flutter: ^1.0.0
  octopus:
    git:
      url: https://github.com/altynbek132/octopus
  l: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9

  flutter_lints: ">=4.0.0 <6.0.0"

  # Generators
  build_runner: ^2.4.8
  # dart_code_metrics: ^5.7.6
